config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
  get "tasks", to: "task#index", as: :tasks
  post "tasks/create", to: "task#create", as: :tasks_create
  patch "tasks/edit/:id", to: "task#update", as: :tasks_update
  patch "tasks/done/:id", to: "task#done", as: :tasks_done
  patch "tasks/undone/:id", to: "task#undone", as: :tasks_undone
  delete "tasks/:id", to: "task#destroy", as: :tasks_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :user, presence: true
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if user_signed_in?
            redirect_to tasks_path
        end
    end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :check_user
  def index
    @tasks = Task.where(:user => current_user.email)
    @task = Task.new
  end

  def create
    task = Task.new(get_task_params)
    task.done = false
    task.user = current_user.email

    if task.save
      redirect_to tasks_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def update
    task = Task.where(:id => params[:id])

    if task.present?
      task.update(get_task_params)
      redirect_to tasks_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def done
    task = Task.where(:id => params[:id])
    if task.present?
      task.update(done: true)
      redirect_to tasks_path
    end
  end

  def undone
    task = Task.where(:id => params[:id])
    if task.present?
      task.update(done: false)
      redirect_to tasks_path
    end
  end

  def destroy
    id = params[:id]
    Task.destroy(id)
    redirect_to tasks_path
  end

  private
  def get_task_params
    params.require(:task).permit(:text, :done);
  end

  private
  def check_user
    unless user_signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/home/index.html.erb
<div class="w-full h-[100vh] flex flex-col p-6 gap-6 items-center justify-center">
    <h1 id="title" class="text-center text-5xl font-bold text-white">
        TODO APP
    </h1>
    <div class="flex flex-col items-center gap-6">
        <%= link_to "Log In", new_user_session_path, id: "btn1", class: "cursor-pointer hover:bg-white hover:text-black transition-colors text-lg font-medium text-white border-2 border-solid border-white p-1.5 pl-8 pr-8" %>
        <%= link_to "Create Account", new_user_registration_path, id: "btn2", class: "cursor-pointer hover:bg-white hover:text-black transition-colors text-lg font-medium text-white border-2 border-solid border-white p-1.5 pl-8 pr-8" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <main class="w-[100vw] min-h-[100vh] bg-gray-950">
      <p class="notice fixed"><%= notice %></p>
      <p class="alert fixed"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="w-[100vw] p-4 fixed flex items-center gap-6">
  <% if user_signed_in? %>
    <%= link_to "Home", tasks_path, class: "text-white font-semibold text-lg cursor-pointer" %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "text-white font-semibold text-lg cursor-pointer" %>
  <% else %>
    <%= link_to "Home", root_path, class: "text-white font-semibold text-lg cursor-pointer" %>
  <% end %>
</nav>

app/views/task/index.html.erb
<div class="w-full h-[100vh] flex flex-col p-6 gap-6 items-center justify-center">
  <h1 id="title" class="text-center text-3xl md:text-5xl font-bold text-white">
    Your Tasks
  </h1>

  <script defer src="<%= javascript_path "form/form" %>"></script>

  <div id="create" class="block">
    <%= form_with model: @task, url: tasks_create_path do |form| %>
      <% if form.object.errors.any? %>
        <% form.object.errors.full_messages.each do |error| %>
          <p class="text-red-500"><%= error %></p>
        <% end %>
      <% end %>

      <div class="flex items-center gap-2 max-w-[90vw] md:max-w-auto">
        <%= form.text_field :text, placeholder: "Your task ...", class: "text-sm md:text-base bg-slate-900 text-white" %>
        <%= form.button "Create", class: "text-sm md:text-base p-1 pl-5 pr-5 text-white border-white border-2 border-solid hover:bg-white hover:text-black transition-colors" %>
      </div>
  <% end %>
  </div>

  <div id="edit" class="hidden">
    <%= form_with model: @task, method: :patch ,url: tasks_create_path do |form| %>
      <% if form.object.errors.any? %>
        <% form.object.errors.full_messages.each do |error| %>
          <p class="text-red-500"><%= error %></p>
        <% end %>
      <% end %>

      <div class="flex items-center gap-2 max-w-[90vw] md:max-w-auto">
        <%= form.text_field :text, placeholder: "Your task ..." , class: "editform text-sm md:text-base bg-slate-900 text-white w-[48%] md:w-auto" %>
        <%= form.button "Edit", class: "text-sm md:text-base p-1 pl-5 pr-5 text-white border-white border-2 border-solid hover:bg-white hover:text-black transition-colors" %>
        <button type="button" id="cancel" class="text-sm md:text-base p-1 pl-5 pr-5 text-white border-white border-2 border-solid hover:bg-white hover:text-black transition-colors">Cancel</button>
      </div>
    <% end %>
  </div>

  <div class="w-[90vw] md:w-[30rem] h-[25rem] md:h-[35rem] overflow-y-auto border-2 border-solid border-white">
    <% @tasks.each do |task| %>
      <div class="w-full flex items-center justify-between p-4">
        <% if task.done %>
          <%= button_to raw("<s>" + task.text + "</s>"), tasks_undone_path(task.id) , method: :patch ,class: "w-[100%] text-white text-base md:text-lg w-4/5 cursor-pointer" %>
        <% else %>
          <%= button_to raw(task.text), tasks_done_path(task.id) , method: :patch ,class: "w-[100%] text-white text-base md:text-lg w-4/5 cursor-pointer" %>
        <% end %>
        <div class="flex items-center gap-4">
          <button
            id="<%= task.id %>"
            class="task hover:text-black text-white hover:bg-white transition-colors text-sm md:text-base p-0.5 md:p-1 pl-3 md:pl-5 pr-3 md:pr-5 border-2 border-solid border-white">
            Edit
          </button>
          <%= button_to "Delete", tasks_destroy_path(task.id), method: :delete, class: "hover:text-black text-white hover:bg-white transition-colors text-sm md:text-base p-0.5 md:p-1 pl-3 md:pl-5 pr-3 md:pr-5 border-2 border-solid border-white" %>
        </div>
      </div>
    <% end %>
  </div>
</div>